import { HistoryEntry } from './history'

// Export to Markdown
export function exportToMarkdown(entry: HistoryEntry): string {
  const timestamp = new Date(entry.timestamp).toLocaleString()
  
  let markdown = `# AI Analysis Export\n\n`
  markdown += `**Date:** ${timestamp}\n`
  markdown += `**Mode:** ${entry.mode}\n`
  markdown += `**Engine:** ${entry.engine || 'Unknown'}\n\n`
  markdown += `---\n\n`
  markdown += `## Input\n\n${entry.input}\n\n`
  markdown += `---\n\n`
  
  if (typeof entry.output === 'string') {
    markdown += `## Output\n\n${entry.output}\n\n`
  } else {
    // Tri-core results
    if (entry.output.chadrak) {
      markdown += `## Chadrak Core Analysis\n\n${entry.output.chadrak}\n\n`
    }
    if (entry.output.nova) {
      markdown += `## Nova Core Analysis\n\n${entry.output.nova}\n\n`
    }
    if (entry.output.triad) {
      markdown += `## Triad Core Analysis\n\n${entry.output.triad}\n\n`
    }
  }
  
  markdown += `---\n\n`
  markdown += `*Generated by The Keys System Tri-Core AI*\n`
  
  return markdown
}

// Export to JSON
export function exportToJSON(entry: HistoryEntry): string {
  const exportData = {
    timestamp: new Date(entry.timestamp).toISOString(),
    mode: entry.mode,
    engine: entry.engine,
    input: entry.input,
    output: entry.output,
    metadata: {
      exportedAt: new Date().toISOString(),
      version: '1.0',
      source: 'The Keys System Tri-Core AI'
    }
  }
  
  return JSON.stringify(exportData, null, 2)
}

// Export to HTML (for PDF conversion)
export function exportToHTML(entry: HistoryEntry): string {
  const timestamp = new Date(entry.timestamp).toLocaleString()
  
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Analysis Export - ${timestamp}</title>
  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      background: #ffffff;
    }
    
    .header {
      border-bottom: 3px solid #0066cc;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    
    .header h1 {
      font-size: 28px;
      color: #0066cc;
      margin-bottom: 10px;
    }
    
    .meta {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
      gap: 10px;
      font-size: 14px;
      color: #666;
    }
    
    .meta-item {
      background: #f5f5f5;
      padding: 8px 12px;
      border-radius: 4px;
    }
    
    .meta-item strong {
      color: #333;
      display: block;
      font-size: 12px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      margin-bottom: 4px;
    }
    
    .section {
      margin: 30px 0;
    }
    
    .section-title {
      font-size: 20px;
      color: #0066cc;
      margin-bottom: 15px;
      padding-bottom: 8px;
      border-bottom: 2px solid #e5e5e5;
    }
    
    .core-section {
      margin: 25px 0;
      padding: 20px;
      background: #f9f9f9;
      border-left: 4px solid #0066cc;
      border-radius: 4px;
    }
    
    .core-section h3 {
      color: #0066cc;
      font-size: 18px;
      margin-bottom: 12px;
    }
    
    .content {
      white-space: pre-wrap;
      word-wrap: break-word;
      font-size: 15px;
      line-height: 1.8;
    }
    
    .input-content {
      background: #f0f7ff;
      padding: 20px;
      border-radius: 4px;
      border-left: 4px solid #0066cc;
    }
    
    .output-content {
      padding: 15px 0;
    }
    
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #e5e5e5;
      text-align: center;
      color: #999;
      font-size: 13px;
    }
    
    @media print {
      body {
        padding: 20px;
      }
      
      .section {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🧠 AI Analysis Report</h1>
    <div class="meta">
      <div class="meta-item">
        <strong>Date</strong>
        ${timestamp}
      </div>
      <div class="meta-item">
        <strong>Mode</strong>
        ${entry.mode}
      </div>
      <div class="meta-item">
        <strong>Engine</strong>
        ${entry.engine || 'Unknown'}
      </div>
    </div>
  </div>
  
  <div class="section">
    <h2 class="section-title">📝 Input</h2>
    <div class="input-content">
      <div class="content">${escapeHtml(entry.input)}</div>
    </div>
  </div>
  
  <div class="section">
    <h2 class="section-title">🤖 AI Analysis</h2>
`

  if (typeof entry.output === 'string') {
    html += `    <div class="output-content">
      <div class="content">${escapeHtml(entry.output)}</div>
    </div>\n`
  } else {
    if (entry.output.chadrak) {
      html += `    <div class="core-section">
      <h3>⚙️ Chadrak Core - Structural Analysis</h3>
      <div class="content">${escapeHtml(entry.output.chadrak)}</div>
    </div>\n`
    }
    if (entry.output.nova) {
      html += `    <div class="core-section">
      <h3>✨ Nova Core - Narrative Refinement</h3>
      <div class="content">${escapeHtml(entry.output.nova)}</div>
    </div>\n`
    }
    if (entry.output.triad) {
      html += `    <div class="core-section">
      <h3>🎯 Triad Core - Execution Planning</h3>
      <div class="content">${escapeHtml(entry.output.triad)}</div>
    </div>\n`
    }
  }
  
  html += `  </div>
  
  <div class="footer">
    Generated by <strong>The Keys System Tri-Core AI</strong><br>
    Exported on ${new Date().toLocaleString()}
  </div>
</body>
</html>`
  
  return html
}

// Helper function to escape HTML
function escapeHtml(text: string): string {
  const div = document.createElement('div')
  div.textContent = text
  return div.innerHTML
}

// Download file helper
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// Export functions
export function exportEntryAsMarkdown(entry: HistoryEntry): void {
  const markdown = exportToMarkdown(entry)
  const filename = `analysis-${entry.mode}-${Date.now()}.md`
  downloadFile(markdown, filename, 'text/markdown')
}

export function exportEntryAsJSON(entry: HistoryEntry): void {
  const json = exportToJSON(entry)
  const filename = `analysis-${entry.mode}-${Date.now()}.json`
  downloadFile(json, filename, 'application/json')
}

export function exportEntryAsHTML(entry: HistoryEntry): void {
  const html = exportToHTML(entry)
  const filename = `analysis-${entry.mode}-${Date.now()}.html`
  downloadFile(html, filename, 'text/html')
}

// Generate shareable link (encrypted)
export async function generateShareableLink(entry: HistoryEntry): Promise<string> {
  // Compress and encode the entry data
  const jsonString = JSON.stringify({
    mode: entry.mode,
    input: entry.input,
    output: entry.output,
    engine: entry.engine,
    timestamp: entry.timestamp
  })
  
  // Base64 encode
  const encoded = btoa(encodeURIComponent(jsonString))
  
  // Create shareable URL (in production, this would be a backend endpoint)
  const baseUrl = window.location.origin
  const shareUrl = `${baseUrl}?share=${encoded}`
  
  // Copy to clipboard
  await navigator.clipboard.writeText(shareUrl)
  
  return shareUrl
}

// Decode shareable link
export function decodeShareableLink(encodedData: string): HistoryEntry | null {
  try {
    const decoded = decodeURIComponent(atob(encodedData))
    const data = JSON.parse(decoded)
    return {
      id: `shared-${Date.now()}`,
      mode: data.mode,
      input: data.input,
      output: data.output,
      engine: data.engine,
      timestamp: data.timestamp
    }
  } catch (error) {
    console.error('Failed to decode shareable link:', error)
    return null
  }
}

// Batch export multiple entries
export function exportMultipleEntriesAsMarkdown(entries: HistoryEntry[]): void {
  let markdown = `# AI Analysis Collection\n\n`
  markdown += `**Exported:** ${new Date().toLocaleString()}\n`
  markdown += `**Total Entries:** ${entries.length}\n\n`
  markdown += `---\n\n`
  
  entries.forEach((entry, index) => {
    markdown += `# Entry ${index + 1}: ${entry.mode}\n\n`
    markdown += exportToMarkdown(entry)
    markdown += `\n\n---\n\n`
  })
  
  const filename = `analysis-collection-${Date.now()}.md`
  downloadFile(markdown, filename, 'text/markdown')
}

export function exportMultipleEntriesAsJSON(entries: HistoryEntry[]): void {
  const exportData = {
    exportedAt: new Date().toISOString(),
    totalEntries: entries.length,
    version: '1.0',
    source: 'The Keys System Tri-Core AI',
    entries: entries.map(entry => ({
      timestamp: new Date(entry.timestamp).toISOString(),
      mode: entry.mode,
      engine: entry.engine,
      input: entry.input,
      output: entry.output
    }))
  }
  
  const json = JSON.stringify(exportData, null, 2)
  const filename = `analysis-collection-${Date.now()}.json`
  downloadFile(json, filename, 'application/json')
}
